# Name of the GitHub Actions workflow
name: Python Calculator Continuous Integration

# Trigger for the workflow: this workflow will run on any push event to the 'main' branch
on:
  push:
    branches: ["main"]

# Define jobs to be executed by this workflow
jobs:
  # Job identifier and description
  test_on_push:
    # Specify the type of runner (virtual machine) that the job will run on
    runs-on: ubuntu-latest

    # Define the steps the job will execute
    steps:
      # Step 1: Check out the repository code using the checkout action v3
      - uses: actions/checkout@v3

      # Step 2: Set up a Python environment with the specified version
      - name: Setting up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x" # Define the version of Python to use

      # Step 3: Install Python dependencies
      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip  # Update pip to the latest version
          pip install -r requirements.txt  # Install dependencies specified in requirements.txt

      # Step 4: Run tests using pytest
      - name: Testing with pytest
        run: pytest # Execute pytest to run tests
